### ISSUE TITLE
Crash when not logged in (user db missing)

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1947]
Latest master.
My dev box.

1. rm h.db
2. I launch the server (using ./run)
3. Open localhost:5000 in my browser

I get this on the server console:

```
2015-02-13 11:01:24,979 [4714] [h.views:ERROR] AttributeError: 'int' object has no attribute 'startswith'
Traceback (most recent call last):
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 95, in tm_tween
    reraise(*exc_info)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 76, in tm_tween
    response = handler(request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 287, in _authdebug_view
    return view(context, request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/csillag/bf/h/h/api.py", line 84, in search
    return _search(request.params, user)
  File "/home/csillag/bf/h/h/api.py", line 246, in _search
    results = Annotation.search(**search_params)
  File "<whatever>h/local/lib/python2.7/site-packages/annotator/elasticsearch.py", line 169, in search
    return cls.search_raw(q, **kwargs)
  File "<whatever>h/local/lib/python2.7/site-packages/annotator/annotation.py", line 86, in search_raw
    f = authz.permissions_filter(user)
  File "<whatever>h/local/lib/python2.7/site-packages/annotator/authz.py", line 84, in permissions_filter
    if user.id.startswith('group:'):
AttributeError: 'int' object has no attribute 'startswith'
```

And the user name (on the top menu) is displayed as "undefined". Pulling down the menu, it seems to think that we are logged in, it offers "Sign out". However, signing out doesn't work.

Server gives me this:
```
2015-02-13 11:04:49,756 [4932] [h.views:ERROR] TypeError: expected string or buffer
Traceback (most recent call last):
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 95, in tm_tween
    reraise(*exc_info)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 76, in tm_tween
    response = handler(request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 287, in _authdebug_view
    return view(context, request)
  File "<whatever>h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/csillag/bf/h/h/accounts/views.py", line 99, in wrapper
    result = meth()
  File "/home/csillag/bf/h/h/accounts/views.py", line 129, in logout
    user = self.User.get_by_id(self.request, self.request.user)
  File "/home/csillag/bf/h/h/accounts/models.py", line 68, in get_by_id
    match = re.match(r'acct:([^@]+)@{}'.format(request.domain), userid)
  File "<whatever>h/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```

**Comment by aron** [comment]
Looks like the same thing I ran into here: https://github.com/hypothesis/h/commit/d5171606a8dcd43ecf08ee27f5c9b8dfc49fb782

But I don't think the code has changed, since it was first written, so perhaps look into why an int is now being passed to this method, and if that's acceptable.

**Comment by csillag** [comment]
@nickstenning, @tilgovi, your names appear in the [relevant](https://github.com/hypothesis/h/commits/master/h/accounts/views.py) [histories](https://github.com/hypothesis/h/commits/master/h/accounts/models.py). Care to join on this?

**Comment by aron** [comment]
Just for the record, I can't replicate the issue following the instructions in the description. Perhaps there is something else here? An corrupt annotation in elasticsearch perhaps?

**Comment by gergely-ujvari** [comment]
@csillag: Can you provide that user.id?

2015.02.13. 11:25 keltezéssel, Aron Carroll írta:

**Comment by csillag** [comment]
I am guessing more like a session cookie that reference a now non-existing user, or something like that.

**Comment by csillag** [comment]
> Can you provide that user.id?

Extracting it from the attempted (at failed) sign out, it's 1.

**Comment by gergely-ujvari** [comment]
I think this a stupid automatic conversion issue, that we handle the
user.id as a string, but during the retrieving it is tested as being
convertable to an int or not, and if yes, it'll be converted.

2015.02.13. 11:29 keltezéssel, Kristof Csillag írta:

**Comment by aron** [comment]
Okay, reproduced the first stack trace.

1. Ensure you're logged out.
2. Go to http://localhost:5000/stream
3. Create a new account.

The username will now be set to `undefined`. And the above stack traces will be dumped in the console.

I wonder if this was due to recent changes in how the login events work in #1925. We use `autologin` now.

On register this passes the userid to authenticated:

https://github.com/eventray/horus/blob/master/horus/views/__init__.py#L423-L425

Which will then pass that int to remember:

https://github.com/eventray/horus/blob/master/horus/views/__init__.py#L64

**Comment by csillag** [comment]
> Looks like the same thing I ran into here: https://github.com/hypothesis/h/commit/d5171606a8dcd43ecf08ee27f5c9b8dfc49fb782

Yep. Cherry-picking your fix helped me, too.

> But I don't think the code has changed, since it was first written, so perhaps look into why an int is now being passed to this method, and if that's acceptable.

Thanks, but I'll leave that to those who have actually worked with that piece of code.

**Comment by aron** [comment]
> Thanks, but I'll leave that to those who have actually worked with that piece of code.

That's the spirit!
