### ISSUE TITLE
NSQSocketError, Connection refused

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2002]
Seen on current master branch, locally.

This is in the log:
```
[gnsq.reader.annotations.stream-_M2Z2lGEm_M#ephemeral:WARNING] [localhost:4150] connection failed (NSQSocketError(111, 'Connection refused'))
```

So no websocket connection is working.
What's more if you create a new annotation, it throws a new exception, 
which is not handled well, so client does not receive an answer although the annotation itself was saved:
```
2015-03-06 11:29:39,402 [17812] [urllib3.connectionpool:WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(111, 'Connection refused'))': /put?topic=annotations
2015-03-06 11:29:39,403 [17812] [urllib3.connectionpool:WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(111, 'Connection refused'))': /put?topic=annotations
2015-03-06 11:29:39,404 [17812] [urllib3.connectionpool:WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(111, 'Connection refused'))': /put?topic=annotations
2015-03-06 11:29:39,412 [17812] [pyramid_debugtoolbar:ERROR] Exception at http://0.0.0.0:5000/api/annotations
traceback url: http://0.0.0.0:5000/api/_debug_toolbar/exception?token=859fed024fb6e03d977f&tb=139733072278480
Traceback (most recent call last):
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 178, in toolbar_tween
    response = _handler(request)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 94, in tm_tween
    reraise(*exc_info)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 75, in tm_tween
    response = handler(request)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 287, in _authdebug_view
    return view(context, request)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/ujvari/git/13/h/h/api.py", line 130, in create
    _publish_annotation_event(request, annotation, 'create')
  File "/home/ujvari/git/13/h/h/api.py", line 223, in _publish_annotation_event
    queue.publish('annotations', json.dumps(data))
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/gnsq/nsqd.py", line 579, in publish
    return self.publish_http(topic, data)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/gnsq/nsqd.py", line 474, in publish_http
    return self.http_post('/put', fields={'topic': topic}, body=data)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/gnsq/httpclient.py", line 49, in http_post
    return self.http_request('POST', url, **kwargs)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/gnsq/httpclient.py", line 21, in http_request
    response = self.http.request_encode_url(method, url, **kwargs)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 618, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 618, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 618, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 598, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/home/ujvari/git/13/h/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPConnectionPool(host='localhost', port=4151): Max retries exceeded with url: /put?topic=annotations (Caused by ProtocolError('Connection aborted.', error(111, 'Connection refused')))
```

**Comment by gergely-ujvari** [comment]
PR https://github.com/hypothesis/h/pull/1986 has introduced this issue.

**Comment by tilgovi** [comment]
Need to pull the queue usage out of h.api.
This was the advantage of the `AnnotationEvent` we got rid of.

**Comment by gergely-ujvari** [comment]
Setting this as a blocker.

**Comment by nickstenning** [comment]
Wait, we don't need to pull it out, we just need to make it optional, right?

**Comment by nickstenning** [comment]
Unmarked as a blocker, as the error messages don't break anything, they're just ugly.

**Comment by gergely-ujvari** [comment]
Realtime notifications are not working. This is a blocker.

**Comment by nickstenning** [comment]
Realtime notifications work just fine if you have nsqd running. Saying the application doesn't work if you don't install postgres doesn't make it a blocker.

**Comment by gergely-ujvari** [comment]
Well, that can be true, however then we need to update our documentation which is nowhere talking about this. (And wasn't like that before)

**Comment by gergely-ujvari** [comment]
Our documentation was updated since then. (I.e. in https://github.com/hypothesis/h/commit/5a27ab529d61231aa8fdc30859fbefc94945933a )

Closing.
