### ISSUE TITLE
Crash on boot (problem with browserify and node-uuid)

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2021]
H does not start.

The gist of the error message is:
```
FilterError: browserify: subprocess returned a non-success result code: 1, stdout=Error: Cannot find module 'node-uuid' from '<whatever>/h/h/static/scripts'
  at <whatever>/h/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
  at process (<whatever>/h/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
  at ondir (<whatever>/h/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
  at load (<whatever>/h/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
  at onex (<whatever>/h/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
  at <whatever>/h/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
  at Object.oncomplete (fs.js:107:15)
```

I am marking this as a blocker.

**Comment by csillag** [comment]
It turns out that since [two hours ago](https://github.com/hypothesis/h/commit/3184311d80b3b3531f4ff1616afaefc2834d394a), we are supposed to separately run `make deps` before `make dev`. 

... and that fixes it. (btw, it would be great if changes like these were announced, either in mails, or preferably in PRs.)
