### ISSUE TITLE
How to run(Please help)

### ISSUE THREAD

**Issue by rathourajay** [hypothesis/h#2085]
I have installed all the dependencies but unable to run it, can anyone suggest command to run this application.
I tried "python worker.py" but it shows "too few argument" .

please suggest with running steps(please give complete command)

Thanks in advance
Ajay singh Rathour

**Comment by tilgovi** [comment]
For development: `make dev`
More generally: `gunicorn --paster conf/<.ini file>`.

**Comment by tilgovi** [comment]
Please join us on our mailing list, (subscribe: mailto:dev+subscribe@list.hypothes.is), and in IRC (#hypothes.is on Freenode) for a better place to get support like this.

**Comment by rathourajay** [comment]
I have tried it. But still not able run this .

Getting following error, I have tried to generate secret key as instruction given in install.rst, but unable to find where to put it exactly.

Here is the error:
Baadmins-MacBook-Pro-4:conf bigdata$ gunicorn  --paster production.ini
Raven is not configured (logging is disabled). Please see the documentation for more information.
2015-03-25 11:17:40,608 [711] [gunicorn.error:INFO] Starting gunicorn 19.3.0
2015-03-25 11:17:40,609 [711] [gunicorn.error:INFO] Listening at: http://127.0.0.1:8000 (711)
2015-03-25 11:17:40,609 [711] [gunicorn.error:INFO] Using worker: h.server.Worker
2015-03-25 11:17:40,933 [714] [gunicorn.error:INFO] Booting worker with pid: 714
2015-03-25 11:17:42,058 [714] [h.app:WARNING] No secret key provided: using transient key. Please configure the secret_key setting or the SECRET_KEY environment variable!
2015-03-25 11:17:42,615 [714] [gunicorn.error:ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/app/wsgiapp.py", line 63, in load
    return self.load_pasteapp()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/app/pasterapp.py", line 71, in load_pasteapp
    global_conf=global_conf)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 203, in invoke
    app = context.app_context.create()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h-2c1a92147fc494dad303ec0d2e4337d929b55ecf-py2.7.egg/h/app.py", line 48, in create_app
    config.include('.views')
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h-2c1a92147fc494dad303ec0d2e4337d929b55ecf-py2.7.egg/h/views.py", line 155, in includeme
    config.include('h.assets')
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h-2c1a92147fc494dad303ec0d2e4337d929b55ecf-py2.7.egg/h/assets.py", line 98, in includeme
    config.include('pyramid_webassets')
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid_webassets-0.9-py2.7.egg/pyramid_webassets/__init__.py", line 375, in includeme
    assets_env = get_webassets_env_from_settings(settings)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid_webassets-0.9-py2.7.egg/pyramid_webassets/__init__.py", line 320, in get_webassets_env_from_settings
    lines = [text(line).rstrip() for line in fin]
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fileinput.py", line 252, in next
    line = self.readline()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fileinput.py", line 342, in readline
    self._file = self._openhook(self._filename, self._mode)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid_webassets-0.9-py2.7.egg/pyramid_webassets/__init__.py", line 314, in yaml_stream
    return assets_env.resolver.resolver.resolve(fname).stream()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/path.py", line 402, in stream
    return self.pkg_resources.resource_stream(self.pkg_name, self.path)
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1085, in resource_stream
    self, resource_name
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1640, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
IOError: [Errno 2] No such file or directory: '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h-2c1a92147fc494dad303ec0d2e4337d929b55ecf-py2.7.egg/h/assets.yaml'
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/app/wsgiapp.py", line 63, in load
    return self.load_pasteapp()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/app/pasterapp.py", line 71, in load_pasteapp
    global_conf=global_conf)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 203, in invoke
    app = context.app_context.create()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h-2c1a92147fc494dad303ec0d2e4337d929b55ecf-py2.7.egg/h/app.py", line 48, in create_app
    config.include('.views')
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h-2c1a92147fc494dad303ec0d2e4337d929b55ecf-py2.7.egg/h/views.py", line 155, in includeme
    config.include('h.assets')
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h-2c1a92147fc494dad303ec0d2e4337d929b55ecf-py2.7.egg/h/assets.py", line 98, in includeme
    config.include('pyramid_webassets')
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid_webassets-0.9-py2.7.egg/pyramid_webassets/__init__.py", line 375, in includeme
    assets_env = get_webassets_env_from_settings(settings)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid_webassets-0.9-py2.7.egg/pyramid_webassets/__init__.py", line 320, in get_webassets_env_from_settings
    lines = [text(line).rstrip() for line in fin]
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fileinput.py", line 252, in next
    line = self.readline()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fileinput.py", line 342, in readline
    self._file = self._openhook(self._filename, self._mode)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid_webassets-0.9-py2.7.egg/pyramid_webassets/__init__.py", line 314, in yaml_stream
    return assets_env.resolver.resolver.resolve(fname).stream()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/path.py", line 402, in stream
    return self.pkg_resources.resource_stream(self.pkg_name, self.path)
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1085, in resource_stream
    self, resource_name
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1640, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
IOError: [Errno 2] No such file or directory: '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h-2c1a92147fc494dad303ec0d2e4337d929b55ecf-py2.7.egg/h/assets.yaml'
2015-03-25 11:17:42,617 [714] [gunicorn.error:INFO] Worker exiting (pid: 714)
2015-03-25 11:17:42,672 [711] [gunicorn.error:INFO] Shutting down: Master
2015-03-25 11:17:42,672 [711] [gunicorn.error:INFO] Reason: Worker failed to boot.

**Comment by tilgovi** [comment]
If you are just trying to start developing, you should try with
conf/development.ini first. It requires fewer things (no redis, no nsdq, no
email).

The simplest way to do that is to run `make dev`.
