### ISSUE TITLE
No warning when trying to use on chrome://extensions/ pages

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2165]
... which is fordibben, so results in an error:

```
extensions::sendRequest:82 Unchecked runtime.lastError while running tabs.executeScript: The extensions gallery cannot be scripted.
    at chrome-extension://lcknipjijijafjbionbfpoehnlfdknhh/lib/sidebar-injector.js:180:27
    at isSidebarInjected (chrome-extension://lcknipjijijafjbionbfpoehnlfdknhh/lib/sidebar-injector.js:179:14)
    at chromeTabs.executeScript.code (chrome-extension://lcknipjijijafjbionbfpoehnlfdknhh/lib/sidebar-injector.js:160:16)
    at removeFromHTML (chrome-extension://lcknipjijijafjbionbfpoehnlfdknhh/lib/sidebar-injector.js:155:14)
    at SidebarInjector.removeFromTab (chrome-extension://lcknipjijijafjbionbfpoehnlfdknhh/lib/sidebar-injector.js:56:16)
    at Object.updateTabDocument [as callback] (chrome-extension://lcknipjijijafjbionbfpoehnlfdknhh/lib/hypothesis-chrome-extension.js:161:24)
```

**Comment by tilgovi** [comment]
Updated the issue title.

**Comment by mbbaig** [comment]
Hi

I would like to get started working on this bug. Would anyone give me some directions as to where I can start?

Thanks

**Comment by tilgovi** [comment]
Unfortunately, I'm not sure this is even still a bug. I just tried to launch the Chrome extension on a chrome-extension URL and got the red error icon on the action button. When clicking it I got the proper screen saying

"We’re sorry, Hypothesis doesn’t work on this page…

This extension can only be used on pages served over HTTP/HTTPS and FTP."

**Comment by tilgovi** [comment]
Tentatively closing this unless @csillag can clarified and reproduce. Thanks for your help, @mbbaig ;).

Happy to help you find other things, though. We have a label, "New Contributor Friendly", where you might find some nice ones to work on while you get more familiar with the code, or chat with us in IRC.

**Comment by mbbaig** [comment]
Well then. Great first bug I guess :).

@tilgovi thanks I'll look into it :+1:

**Comment by csillag** [comment]
> Tentatively closing this unless @csillag can clarified and reproduce.

No, it's really solved.
