### ISSUE TITLE
QueryParsingException: No text specified for text query

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2257]
After setting `h.feature.queue: True` and `h.feature.streamer: True` to get around [another issue](https://github.com/hypothesis/h/issues/2256) I'm getting the traceback below on master.

In the `send_annotations()` method in `streamer.py` on line 470 `self.query.query["query"]["bool"]["should"][0]["match"]["uri"]["query"]` is an empty list, and elasticsearch doesn't like this. Appending an arbitrary string to the list gets rid of the traceback.

In tracing where this empty list comes from: it seems to come into streamer.py via greenlet.py and websocket.py as a message. Not sure who sends it.

```
Traceback (most recent call last):
  File "/home/seanh/Projects/hypothesis/h/h/streamer.py", line 526, in received_message
    self.send_annotations()
  File "/home/seanh/Projects/hypothesis/h/h/streamer.py", line 470, in send_annotations
    annotations = Annotation.search_raw(query=self.query.query, user=user)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/annotator/annotation.py", line 91, in search_raw
    raw_result=raw_result)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/annotator/elasticsearch.py", line 182, in search_raw
    **params)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 504, in search
    params=params, body=body)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 89, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[7CUYOw9XQrawDz6ws_s_Dg][annotator][0]: SearchParseException[[annotator][0]: from[-1],size[-1],sort[<custom:"updated": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@d5d0ade>!]: Parse Failure [Failed to parse source [{"sort": [{"updated": {"order": "desc"}}], "query": {"filtered": {"filter": {"term": {"permissions.read": "group:__world__"}}, "query": {"bool": {"should": [{"match": {"uri": {"operator": "and", "query": []}}}], "minimum_number_should_match": 1}}}}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[annotator] No text specified for text query]; }{[7CUYOw9XQrawDz6ws_s_Dg][annotator][1]: SearchParseException[[annotator][1]: from[-1],size[-1],sort[<custom:"updated": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@57747bac>!]: Parse Failure [Failed to parse source [{"sort": [{"updated": {"order": "desc"}}], "query": {"filtered": {"filter": {"term": {"permissions.read": "group:__world__"}}, "query": {"bool": {"should": [{"match": {"uri": {"operator": "and", "query": []}}}], "minimum_number_should_match": 1}}}}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[annotator] No text specified for text query]; }{[7CUYOw9XQrawDz6ws_s_Dg][annotator][2]: SearchParseException[[annotator][2]: from[-1],size[-1],sort[<custom:"updated": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@2063860f>!]: Parse Failure [Failed to parse source [{"sort": [{"updated": {"order": "desc"}}], "query": {"filtered": {"filter": {"term": {"permissions.read": "group:__world__"}}, "query": {"bool": {"should": [{"match": {"uri": {"operator": "and", "query": []}}}], "minimum_number_should_match": 1}}}}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[annotator] No text specified for text query]; }{[7CUYOw9XQrawDz6ws_s_Dg][annotator][3]: SearchParseException[[annotator][3]: from[-1],size[-1],sort[<custom:"updated": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@4d7f405e>!]: Parse Failure [Failed to parse source [{"sort": [{"updated": {"order": "desc"}}], "query": {"filtered": {"filter": {"term": {"permissions.read": "group:__world__"}}, "query": {"bool": {"should": [{"match": {"uri": {"operator": "and", "query": []}}}], "minimum_number_should_match": 1}}}}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[annotator] No text specified for text query]; }{[7CUYOw9XQrawDz6ws_s_Dg][annotator][4]: SearchParseException[[annotator][4]: from[-1],size[-1],sort[<custom:"updated": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@2ddd5c89>!]: Parse Failure [Failed to parse source [{"sort": [{"updated": {"order": "desc"}}], "query": {"filtered": {"filter": {"term": {"permissions.read": "group:__world__"}}, "query": {"bool": {"should": [{"match": {"uri": {"operator": "and", "query": []}}}], "minimum_number_should_match": 1}}}}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[annotator] No text specified for text query]; }]')
```

**Comment by judell** [comment]
Still an issue? What was the URL that provoked this traceback?

**Comment by seanh** [comment]
I'm still getting this on master: just turn on qeuue and streamer and visit any page (e.g. the /welcome page). Haven't had time to look into it
