### ISSUE TITLE
[172.17.11.122:4150] error requeueing message (NSQSocketError(32, 'Broken pipe'))

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2304]
https://app.getsentry.com/hypothesis/prod/group/64537044/

This is particularly suspicious. The first time we saw this was... May 6.

https://app.getsentry.com/hypothesis/prod/group/64537044/events/3648193236/

Then saw it a couple of times while clearing the backlog on Sunday:

https://app.getsentry.com/hypothesis/prod/group/64537044/events/3675935875/
https://app.getsentry.com/hypothesis/prod/group/64537044/events/3675935887/
https://app.getsentry.com/hypothesis/prod/group/64537044/events/3675937435/

And finally saw it today about 31 minutes ago:

https://app.getsentry.com/hypothesis/prod/group/64537044/events/3678482591/

If I check nsq right now, I see that one of the client connections to the `notification` channel has been connected for 31 minutes and has a `RDY` of zero!

![screen shot 2015-06-09 at 19 37 45](https://cloud.githubusercontent.com/assets/3602/8065055/2a4175cc-0edf-11e5-9fae-bf1b50071256.png)

That's too much coincidence for my liking :)

**Comment by nickstenning** [comment]
It was `prod` (rather than `stream`) that had failed. Here's the full log, which is sadly rather noisy.

https://gist.github.com/nickstenning/061e81fd15b6e3b015a8

**Comment by nickstenning** [comment]
Okay, this is clearly what's causing the problem. It happened [24 minutes ago](https://app.getsentry.com/hypothesis/prod/group/64537044/events/3679572949/) and again one of the connections to NSQ has been around for 24 minutes and has a `RDY` of zero.

**Comment by nickstenning** [comment]
```
ubuntu@ip-10-222-217-195:~$ dokku logs prod
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 12

Traceback (most recent call last):
  File "/srv/h/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 658, in handle
    handler.handle()
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 184, in handle
    result = self.handle_one_request()
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 321, in handle_one_request
    self.handle_one_response()
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 518, in handle_one_response
    self.log_request()
  File "/srv/h/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 219, in log_request
    self.server.log.access(resp, req_headers, self.environ, response_time)
  File "/srv/h/local/lib/python2.7/site-packages/gunicorn/instrument/statsd.py", line 96, in access
    self.increment("gunicorn.request.status.%d" % int(resp.status.split()[0]), 1)
ValueError: invalid literal for int() with base 10: 'socket'
<Greenlet at 0x7f2401d90910: <bound method WSGIServer.handle of <WSGIServer at 0x7f2402eeb590 fileno=6 address=0.0.0.0:8000>>(<socket at 0x7f2400a5b390 fileno=[Errno 9] Bad fil, ('172.17.42.1', 46937))> failed with ValueError

Traceback (most recent call last):
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/srv/h/local/lib/python2.7/site-packages/ws4py/server/geventserver.py", line 62, in run_application
    gevent.pywsgi.WSGIHandler.run_application(self)
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 495, in run_application
    self.process_result()
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 486, in process_result
    self.write(data)
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 380, in write
    self._write_with_headers(data)
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 400, in _write_with_headers
    self._sendall(towrite)
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 355, in _sendall
    self.socket.sendall(data)
  File "/srv/h/local/lib/python2.7/site-packages/gevent/socket.py", line 458, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/srv/h/local/lib/python2.7/site-packages/gevent/socket.py", line 435, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-us',
 'HTTP_CONNECTION': 'upgrade',
 'HTTP_COOKIE': '_ga=GA1.2.400699366.1433938771; _gat=1; session=2ae477a11a30fd5a52e739385c79c17b6345c173gAJVQDYyZjI2YTc2NDNiMTdmYmNiNzI0ZTZjNzEyYmRmNjYzYWQ0MTU4ZmEyZGIzY2ViOTkxZGNkMWMzZjQ2ZThkOGJxAS4=; XSRF-TOKEN=d023897da9cc200690bdbcee5b67841ec07d275d',
 'HTTP_HOST': 'hypothes.is',
 'HTTP_REFERER': 'https://hypothes.is/viewer',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4',
 'HTTP_X_REAL_IP': '10.222.97.99',
 'PATH_INFO': '/assets/scripts/app.min.js',
 'QUERY_STRING': 'b3366d2c',
 'RAW_URI': '/assets/scripts/app.min.js?b3366d2c',
 'REMOTE_ADDR': '10.222.97.99',
 'REMOTE_PORT': '46939',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '1108b279dfa8',
 'SERVER_PORT': '8000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0.1 gunicorn/19.3.0',
 'gunicorn.sock': <socket at 0x7f24008278d0 fileno=24 sock=172.17.12.227:8000>,
 'webob._parsed_cookies': ({u'XSRF-TOKEN': u'd023897da9cc200690bdbcee5b67841ec07d275d',
                            u'_ga': u'GA1.2.400699366.1433938771',
                            u'_gat': u'1',
                            u'session': u'2ae477a11a30fd5a52e739385c79c17b6345c173gAJVQDYyZjI2YTc2NDNiMTdmYmNiNzI0ZTZjNzEyYmRmNjYzYWQ0MTU4ZmEyZGIzY2ViOTkxZGNkMWMzZjQ2ZThkOGJxAS4='},
                           '_ga=GA1.2.400699366.1433938771; _gat=1; session=2ae477a11a30fd5a52e739385c79c17b6345c173gAJVQDYyZjI2YTc2NDNiMTdmYmNiNzI0ZTZjNzEyYmRmNjYzYWQ0MTU4ZmEyZGIzY2ViOTkxZGNkMWMzZjQ2ZThkOGJxAS4=; XSRF-TOKEN=d023897da9cc200690bdbcee5b67841ec07d275d'),
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f2402eeb550>,
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7f24008a3e50>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)} failed with error

Traceback (most recent call last):
  File "/srv/h/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 658, in handle
    handler.handle()
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 184, in handle
    result = self.handle_one_request()
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 321, in handle_one_request
    self.handle_one_response()
  File "/srv/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 518, in handle_one_response
    self.log_request()
  File "/srv/h/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 219, in log_request
    self.server.log.access(resp, req_headers, self.environ, response_time)
  File "/srv/h/local/lib/python2.7/site-packages/gunicorn/instrument/statsd.py", line 96, in access
    self.increment("gunicorn.request.status.%d" % int(resp.status.split()[0]), 1)
ValueError: invalid literal for int() with base 10: 'socket'
<Greenlet at 0x7f2401d905f0: <bound method WSGIServer.handle of <WSGIServer at 0x7f2402eeb590 fileno=6 address=0.0.0.0:8000>>(<socket at 0x7f24008278d0 fileno=[Errno 9] Bad fil, ('172.17.42.1', 46939))> failed with ValueError

Jun 10 13:17:01 1108b279dfa8 /USR/SBIN/CRON[455]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
/srv/h/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/srv/h/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'acct:chungpark@hypothes.i...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
Jun 10 14:17:01 1108b279dfa8 /USR/SBIN/CRON[458]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun 10 15:17:01 1108b279dfa8 /USR/SBIN/CRON[461]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
```

**Comment by nickstenning** [comment]
Seems to have been `stream` this time.

**Comment by nickstenning** [comment]
It seems rather tricky to trigger what appears to be the problem, namely, from [line 699 of `reader.py`](https://github.com/wtolson/gnsq/blob/3a6016/gnsq/reader.py#L699):

```
[172.17.11.122:4150] error requeueing message (NSQSocketError(32, 'Broken pipe'))
```

Which would imply that `message.has_responded()` a few lines above has returned false. That would seem to imply that we're seeing networking issues. I've tried to reproduce this with [blockade](https://github.com/dcm-oss/blockade) (see [this repo](https://github.com/nickstenning/gnsq-blockade)) to no avail so far.

**Comment by nickstenning** [comment]
b550071 deployed to production. Closing.
