### ISSUE TITLE
Background page errors when closing PDF tab in Chrome extension

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3095]
### Steps to reproduce
1. Go to https://via.hypothes.is/http://users.clas.ufl.edu/burt/KafkaKierkegaardBible/BorgesTheCircularRuins.pdf
2. Activate the H Chrome extension, open the background page for the extension under chrome://extensions
3. Close the tab opened in step 1.
### Expected behaviour

No errors in the Chrome extension background page
### Actual behaviour

This error is seen in the Chrome extension background page and reported to Sentry:

```
extensions::uncaught_exception_handler:8 Error in response to tabs.get: TypeError: Cannot read property 'id' of undefined
    at Object.updateTabDocument [as callback] (chrome-extension://fnakljiimkbcofknbibfdhboljildojm/lib/extension.bundle.js:495:28)
    at TabState.onTabStateChange [as onchange] (chrome-extension://fnakljiimkbcofknbibfdhboljildojm/lib/extension.bundle.js:403:18)
    at TabState.setState (chrome-extension://fnakljiimkbcofknbibfdhboljildojm/lib/extension.bundle.js:1050:13)
    at Object.updateTabDocument [as callback] (chrome-extension://fnakljiimkbcofknbibfdhboljildojm/lib/extension.bundle.js:503:13)handler @ extensions::uncaught_exception_handler:8(anonymous function) @ extensions::uncaught_exception_handler:100safeCallbackApply @ extensions::sendRequest:23handleResponse @ extensions::sendRequest:72
extensions::lastError:133 Unchecked runtime.lastError while running tabs.get: No tab with id: 231.
    at TabState.onTabStateChange [as onchange] (chrome-extension://fnakljiimkbcofknbibfdhboljildojm/lib/extension.bundle.js:403:18)
    at TabState.setState (chrome-extension://fnakljiimkbcofknbibfdhboljildojm/lib/extension.bundle.js:1050:13)
    at Object.updateTabDocument [as callback] (chrome-extension://fnakljiimkbcofknbibfdhboljildojm/lib/extension.bundle.js:503:13)reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78
2extensions::lastError:133 Unchecked runtime.lastError while running browserAction.setIcon: No tab with id: 231.
```
### Browser/system information

Chrome 50 under Ubuntu 15.10

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/browser-extension/issues/24.
