### ISSUE TITLE
Cannot start h, having a database exception on startup

### ISSUE THREAD

**Issue by MswTech** [hypothesis/h#3182]
Hi, 

I'm trying to run h but I get an exception when h is trying to start in the docker container 

All the stack is orchestrated by docker-compose and all containers are linked to hypothesis container, meaning h has access to postgres, elasticsearch, ...
 
### Steps to reproduce
1. Run h docker container
2. Watch the logs

### Expected behaviour
Hypothesis should start and be available ...

### Actual behaviour
....but crashes with the following database related exception : 
```
2016-04-07 01:35:52,705 [17] [gunicorn.error:ERROR] Exception in worker process:
hypothesis_1 | Traceback (most recent call last):
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
hypothesis_1 |     worker.init_process()
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
hypothesis_1 |     self.load_wsgi()
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
hypothesis_1 |     self.wsgi = self.app.wsgi()
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
hypothesis_1 |     self.callable = self.load()
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 63, in load
hypothesis_1 |     return self.load_pasteapp()
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
hypothesis_1 |     return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/gunicorn/app/pasterapp.py", line 69, in load_pasteapp
hypothesis_1 |     global_conf=global_conf)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
hypothesis_1 |     return loadobj(APP, uri, name=name, **kw)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
hypothesis_1 |     return context.create()
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
hypothesis_1 |     return self.object_type.invoke(self)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 203, in invoke
hypothesis_1 |     app = context.app_context.create()
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
hypothesis_1 |     return self.object_type.invoke(self)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
hypothesis_1 |     return fix_call(context.object, context.global_conf, **context.local_conf)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
hypothesis_1 |     val = callable(*args, **kw)
hypothesis_1 |   File "/var/lib/hypothesis/h/app.py", line 46, in create_app
hypothesis_1 |     return config.make_wsgi_app()
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/pyramid/config/__init__.py", line 995, in make_wsgi_app
hypothesis_1 |     self.registry.notify(ApplicationCreated(app))
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/pyramid/registry.py", line 91, in notify
hypothesis_1 |     [ _ for _ in self.subscribers(events, None) ]
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/zope/interface/registry.py", line 328, in subscribers
hypothesis_1 |     return self.adapters.subscribers(objects, provided)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/zope/interface/adapter.py", line 596, in subscribers
hypothesis_1 |     subscription(*objects)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/pyramid/config/adapters.py", line 103, in derived_subscriber
hypothesis_1 |     return subscriber(arg[0])
hypothesis_1 |   File "/var/lib/hypothesis/h/features.py", line 212, in remove_old_flags_on_boot
hypothesis_1 |     remove_old_flags()
hypothesis_1 |   File "/var/lib/hypothesis/h/features.py", line 199, in remove_old_flags
hypothesis_1 |     count = unknown_flags.delete(synchronize_session=False)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3048, in delete
hypothesis_1 |     delete_op.exec_()
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1127, in exec_
hypothesis_1 |     self._do_exec()
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1311, in _do_exec
hypothesis_1 |     mapper=self.mapper)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1034, in execute
hypothesis_1 |     bind, close_with_result=True).execute(clause, params or {})
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
hypothesis_1 |     return meth(self, multiparams, params)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
hypothesis_1 |     return connection._execute_clauseelement(self, multiparams, params)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
hypothesis_1 |     compiled_sql, distilled_params
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
hypothesis_1 |     context)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
hypothesis_1 |     exc_info
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
hypothesis_1 |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
hypothesis_1 |     context)
hypothesis_1 |   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
hypothesis_1 |     cursor.execute(statement, parameters)
hypothesis_1 | ProgrammingError: (psycopg2.ProgrammingError) relation "feature" does not exist
hypothesis_1 | LINE 1: DELETE FROM feature WHERE feature.name NOT IN ('claim', 'ops...
```

### Additional details
```
docker exec -ti d1741acf66ef_hypothesisstack_postgres_1 postgres --version
postgres (PostgreSQL) 9.5.2
```
Could be the same issue as #3073

**Comment by MswTech** [comment]
I resolved my problem by forcing the MODEL_CREATE_ALL env var at startup. Found the solution on the IRC channel.
