### ISSUE TITLE
AttributeError when processing requests when not logged in

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3477]
Load any page (e.g. localhost:5000 or localhost:5000/docs/help) while not logged in:

```
Traceback (most recent call last):
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 209, in toolbar_tween
    response = _handler(request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/tweens.py", line 48, in excview_tween
    request_iface=request_iface.combined
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 602, in __call__
    return view(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 286, in _authdebug_view
    return view(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 353, in rendered_view
    result = view(context, request)
  File "/home/seanh/Projects/hypothesis/h/h/views/exceptions.py", line 50, in json_error
    _handle_exc(request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/seanh/Projects/hypothesis/h/h/tweens.py", line 24, in conditional_http_tween
    response = handler(request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 602, in __call__
    return view(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 286, in _authdebug_view
    return view(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 217, in wrapper
    response = view(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 353, in rendered_view
    result = view(context, request)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/pyramid/config/views.py", line 507, in _requestonly_view
    response = view(request)
  File "/home/seanh/Projects/hypothesis/h/h/views/client.py", line 74, in session_view
    model = h_session.model(request)
  File "/home/seanh/Projects/hypothesis/h/h/session.py", line 12, in model
    session['features'] = request.feature.all()
  File "/home/seanh/Projects/hypothesis/h/h/features/client.py", line 58, in all
    self._load()
  File "/home/seanh/Projects/hypothesis/h/h/features/client.py", line 68, in _load
    self._cache = {f.name: self._state(f) for f in features}
  File "/home/seanh/Projects/hypothesis/h/h/features/client.py", line 68, in <dictcomp>
    self._cache = {f.name: self._state(f) for f in features}
  File "/home/seanh/Projects/hypothesis/h/h/features/client.py", line 82, in _state
    if set(feature.cohorts) & set(self.request.authenticated_user.cohorts):
AttributeError: 'NoneType' object has no attribute 'cohorts'
```

**Comment by seanh** [comment]
Already fixed by https://github.com/hypothesis/h/pull/3476
