### ISSUE TITLE
Celery is not booting correctly

### ISSUE THREAD

**Issue by rickyhan** [hypothesis/h#4134]
This is the output running `make dev`

```
18:52:51 beat   | celery beat v3.1.25 (Cipater) is starting.
18:52:51 worker | /root/h/.venv/local/lib/python2.7/site-packages/celery/platforms.py:812: RuntimeWarning: You are running the worker with superuser privileges, which is
18:52:51 worker | absolutely not recommended!
18:52:51 worker |
18:52:51 worker | Please specify a different user using the -u option.
18:52:51 worker |
18:52:51 worker | User information: uid=0 euid=0 gid=0 egid=0
18:52:51 worker |
18:52:51 worker |   uid=uid, euid=euid, gid=gid, egid=egid,
18:52:51 beat   | __    -    ... __   -        _
18:52:51 beat   | Configuration ->
18:52:51 beat   |     . broker -> amqp://guest:**@localhost:5672//
18:52:51 beat   |     . loader -> celery.loaders.app.AppLoader
18:52:51 beat   |     . scheduler -> celery.beat.PersistentScheduler
18:52:51 beat   |     . db -> celerybeat-schedule
18:52:51 beat   |     . logfile -> [stderr]@%INFO
18:52:51 beat   |     . maxinterval -> now (0s)
18:52:51 beat   | [2016-11-28 18:52:51,203: INFO/MainProcess] beat: Starting...
18:52:51 assets | [18:52:51] Using gulpfile ~/h/gulpfile.js
18:52:51 assets | [18:52:51] Starting 'build-vendor-js'...
18:52:51 assets | [18:52:51] Starting 'watch-css'...
18:52:52 assets | [18:52:52] Finished 'watch-css' after 402 ms
18:52:52 assets | [18:52:52] Starting 'watch-fonts'...
18:52:52 assets | [18:52:52] Finished 'watch-fonts' after 2.6 ms
18:52:52 assets | [18:52:52] Starting 'watch-images'...
18:52:52 assets | [18:52:52] Finished 'watch-images' after 337 ms
18:52:52 assets | [18:52:52] Starting 'watch-manifest'...
18:52:52 assets | [18:52:52] Finished 'watch-manifest' after 133 ms
18:52:54 web    | 2016-11-28 18:52:54,098 [20089] [gunicorn.error:ERROR] Exception in worker process
18:52:54 web    | Traceback (most recent call last):
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
18:52:54 web    |     worker.init_process()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
18:52:54 web    |     self.load_wsgi()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
18:52:54 web    |     self.wsgi = self.app.wsgi()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
18:52:54 web    |     self.callable = self.load()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 63, in load
18:52:54 web    |     return self.load_pasteapp()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
18:52:54 web    |     return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/gunicorn/app/pasterapp.py", line 69, in load_pasteapp
18:52:54 web    |     global_conf=global_conf)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
18:52:54 web    |     return loadobj(APP, uri, name=name, **kw)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
18:52:54 web    |     return context.create()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
18:52:54 web    |     return self.object_type.invoke(self)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 203, in invoke
18:52:54 web    |     app = context.app_context.create()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
18:52:54 web    |     return self.object_type.invoke(self)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
18:52:54 web    |     return fix_call(context.object, context.global_conf, **context.local_conf)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 58, in fix_call
18:52:54 web    |     reraise(*exc_info)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/paste/deploy/compat.py", line 23, in reraise
18:52:54 web    |     exec('raise t, e, tb', dict(t=t, e=e, tb=tb))
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
18:52:54 web    |     val = callable(*args, **kw)
18:52:54 web    |   File "/root/h/h/app.py", line 35, in create_app
18:52:54 web    |     return config.make_wsgi_app()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 985, in make_wsgi_app
18:52:54 web    |     self.commit()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 654, in commit
18:52:54 web    |     self.action_state.execute_actions(introspector=self.introspector)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 1163, in execute_actions
18:52:54 web    |     action = next(pending_actions, None)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 1121, in resume
18:52:54 web    |     for a, b in zip_longest(actions, executed_actions):
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 1255, in resolveConflicts
18:52:54 web    |     discriminator = undefer(action['discriminator'])
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/registry.py", line 271, in undefer
18:52:54 web    |     v = v.resolve()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/registry.py", line 263, in resolve
18:52:54 web    |     return self.value
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/decorator.py", line 42, in __get__
18:52:54 web    |     val = self.wrapped(inst)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/registry.py", line 260, in value
18:52:54 web    |     return self.func()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 812, in discrim_func
18:52:54 web    |     order, preds, phash = predlist.make(self, **pvals)
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/config/util.py", line 160, in make
18:52:54 web    |     hashes = pred.phash()
18:52:54 web    |   File "/root/h/.venv/local/lib/python2.7/site-packages/pyramid/config/predicates.py", line 42, in text
18:52:54 web    |     return 'request_method = %s' % (','.join(self.val))
18:52:54 web    | TypeError: sequence item 0: expected string, list found
18:52:54 web    | 2016-11-28 18:52:54,113 [20089] [gunicorn.error:INFO] Worker exiting (pid: 20089)
```

**Comment by nickstenning** [comment]
Are you running an unmodified version of h? That looks like pyramid is complaining about an invalid `request_method` view predicate, but I can't reproduce the error on a current checkout.

It would helpful to see the output of:

- `hypothesis --version`
- `pip list`

**Comment by rickyhan** [comment]
Thanks for your help. I got it to work again after changing `request_method=['GET','POST]` to a tuple `request_method=('GET','POST')`
