### ISSUE TITLE
https://via.hypothes.is/https://threatpost.com/ does not work

### ISSUE THREAD

**Issue by volth** [hypothesis/h#4218]
https://via.hypothes.is/https://threatpost.com/ (or any url on threatpost.com) returns HTTP Error 502; it is not a temporary downtime, I tried many times with big intervals.

**Comment by ajpeddakotla** [comment]
@volth thanks for letting us know about this. We've tried this on our end and are able to reproduce the 502 with is particular URLs, but not with others. 

Are there other URLs that you've also come across that are failing? If you do find more, that will help us characterize the issue and figure out what might be happening.

**Comment by volth** [comment]
I meant the urls like for example https://via.hypothes.is/https://threatpost.com/about-threatpost/ http://via.hypothes.is/https://threatpost.com/contact-us/

**Comment by nickstenning** [comment]
Fixed! https://github.com/hypothesis/playbook/commit/e989b464c4ed9911950b11bda59ea540736074ac (this is in a private repository so I'm afraid you won't be able to see it @volth -- the gist is that threatpost.com sets a gigantic HTTP response header for `Content-Security-Policy` which didn't fit into the buffers allocated for our proxy's webserver configuration.)

**Comment by volth** [comment]
It happens again.
Same URLs, 502 error.

**Comment by volth** [comment]
Another test case https://via.hypothes.is/https://securelist.com/ 
```securelist.com``` is on the same server together with ```threatpost.com```

**Comment by robertknight** [comment]
I tested this in our QA environment where there is less noise from other requests:

From `/var/log/eb-docker/containers/eb-current-app/{id}-stdouterr.log` on the qa-via instance managed by Elastic Beanstalk after trying to request https://qa-via.hypothes.is/https://threadpost.com :

```
web (stderr)         | write error
web (stderr)         | 
web                  | Traceback (most recent call last):
web                  |   File "/var/lib/via/src/pywb/pywb/webapp/live_rewrite_handler.py", line 58, in handle_request
web                  |     return self.render_content(wbrequest)
web                  |   File "/var/lib/via/src/pywb/pywb/webapp/live_rewrite_handler.py", line 120, in render_content
web                  |     verify=self.verify)
web                  |   File "/var/lib/via/src/pywb/pywb/rewrite/rewrite_live.py", line 210, in fetch_request
web                  |     verify)
web                  |   File "/var/lib/via/src/pywb/pywb/rewrite/rewrite_live.py", line 162, in fetch_http
web                  |     verify=verify)
web                  |   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
web                  |     return session.request(method=method, url=url, **kwargs)
web                  |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
web                  |     resp = self.send(prep, **send_kwargs)
web                  |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
web                  |     r = adapter.send(request, **kwargs)
web                  |   File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 502, in send
web                  |     raise ProxyError(e, request=request)
web                  | ProxyError: HTTPSConnectionPool(host='threadpost.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 503 Service Unavailable',)))
web                  | 
```

**Comment by volth** [comment]
Do they banned Amazon IPs ?

**Comment by robertknight** [comment]
>. Do they banned Amazon IPs ?

I can reproduce the issue locally from my machine, so there is definitely an unrelated problem to deal with first.
