### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec…

### ISSUE THREAD

**Issue by jibe-b** [hypothesis/h#4367]
### Steps to reproduce
1. install h following steps from http://h.readthedocs.io/en/latest/developing/install/website/#installing-the-services
2. make dev

### Actual behaviour
>UnicodeEncodeError: 'ascii' codec can't encode character u'\u03bc' in position 68: ordinal not in range(128)

### Browser/system information
Ubuntu 16.04 server, dependencies as requiered except phantomjs

### Additional details

>Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/h/h/__main__.py", line 6, in <module>
    main()
  File "h/cli/__init__.py", line 74, in main
    cli(prog_name='hypothesis', obj={})
  File "/root/h/.venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/root/h/.venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/root/h/.venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/h/.venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/h/.venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "h/cli/commands/devserver.py", line 91, in devserver
    m.loop()
  File "/root/h/.venv/local/lib/python2.7/site-packages/honcho/manager.py", line 116, in loop
    self._printer.write(msg)
  File "/root/h/.venv/local/lib/python2.7/site-packages/honcho/printer.py", line 46, in write
    self.output.write(prefix + line + "\n")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03bc' in position 68: ordinal not in range(128)

I'll try to see if I can solve it by my own.

**Comment by jibe-b** [comment]
Done a few changes and retried and the problem vanished. I can't unfortunately track what solved the issue (as a non-professional).

**Comment by robertknight** [comment]
Hello @jibe-b - It looks like the character 'μ' (\u03bc) appeared _somewhere_ in one of the messages that the development server was trying to print that wasn't handled properly inside honcho.

May relate to https://github.com/nickstenning/honcho/issues/66
