### ISSUE TITLE
/api/token endpoint returns 500 when using JWT grant authorisation if "aud" is invalid

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4957]
### Steps to reproduce
1. Setup the [publisher-account-test-site](https://github.com/hypothesis/publisher-account-test-site) and verify that you can use it with a local h install
2. Change the [code which generates the JWT grant token](https://github.com/hypothesis/publisher-account-test-site/blob/03fa7e7d6373db09d6f9175a46b528c830967638/hypothesis.py#L69) to return a different valid for the `aud` key
3. Try to use the size

### Expected behaviour
h should return a helpful error message in the response when the client tries to authenticate

### Actual behaviour
h throws an exception and returns 500.

<details>

```
10:25:38 web    | 2018-04-09 10:25:38,737 [4135] [pyramid_debugtoolbar:ERROR] Uncaught Exception at http://localhost:5000/api/token
10:25:38 web    | traceback url: http://localhost:5000/_debug_toolbar/34343731353737383438/exception
10:25:38 web    | Traceback (most recent call last):
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/oauth/jwt_grant_token.py", line 72, in _verify
10:25:38 web    |     leeway=self.LEEWAY)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/jwt/api_jwt.py", line 90, in decode
10:25:38 web    |     self._validate_claims(payload, merged_options, **kwargs)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/jwt/api_jwt.py", line 126, in _validate_claims
10:25:38 web    |     self._validate_aud(payload, audience)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/jwt/api_jwt.py", line 181, in _validate_aud
10:25:38 web    |     raise InvalidAudienceError('Invalid audience')
10:25:38 web    | jwt.exceptions.InvalidAudienceError: Invalid audience
10:25:38 web    | 
10:25:38 web    | During handling of the above exception, another exception occurred:
10:25:38 web    | 
10:25:38 web    | Traceback (most recent call last):
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/oauth/jwt_grant.py", line 78, in create_token_response
10:25:38 web    |     self.validate_token_request(request)
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/oauth/jwt_grant.py", line 119, in validate_token_request
10:25:38 web    |     verified_token = token.verified(key=authclient.secret, audience=self.domain)
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/oauth/jwt_grant_token.py", line 45, in verified
10:25:38 web    |     return VerifiedJWTGrantToken(self._token, key, audience)
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/oauth/jwt_grant_token.py", line 62, in __init__
10:25:38 web    |     self._verify(key, audience)
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/oauth/jwt_grant_token.py", line 85, in _verify
10:25:38 web    |     raise errors.InvalidJWTGrantTokenClaimError('aud', 'audience')
10:25:38 web    | h.oauth.errors.InvalidJWTGrantTokenClaimError: ('aud', 'audience')
10:25:38 web    | 
10:25:38 web    | During handling of the above exception, another exception occurred:
10:25:38 web    | 
10:25:38 web    | Traceback (most recent call last):
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid_debugtoolbar/toolbar.py", line 247, in toolbar_tween
10:25:38 web    |     response = _handler(request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
10:25:38 web    |     result = handler(request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/tweens.py", line 51, in excview_tween
10:25:38 web    |     request_iface=request_iface.combined
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/view.py", line 547, in _call_view
10:25:38 web    |     response = view_callable(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/config/views.py", line 182, in __call__
10:25:38 web    |     return view(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 393, in attr_view
10:25:38 web    |     return view(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
10:25:38 web    |     return view(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 330, in _authdebug_view
10:25:38 web    |     return view(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
10:25:38 web    |     result = view(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
10:25:38 web    |     response = view(request)
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/views/api_exceptions.py", line 48, in json_error
10:25:38 web    |     handle_exception(request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/tweens.py", line 22, in excview_tween
10:25:38 web    |     response = handler(request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
10:25:38 web    |     reraise(*exc_info)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid_tm/compat.py", line 15, in reraise
10:25:38 web    |     raise value
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
10:25:38 web    |     response = handler(request)
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/tweens.py", line 20, in conditional_http_tween
10:25:38 web    |     response = handler(request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/router.py", line 158, in handle_request
10:25:38 web    |     view_name
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/view.py", line 547, in _call_view
10:25:38 web    |     response = view_callable(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/config/views.py", line 182, in __call__
10:25:38 web    |     return view(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 393, in attr_view
10:25:38 web    |     return view(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
10:25:38 web    |     return view(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 354, in _authdebug_view
10:25:38 web    |     return view(context, request)
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/util/cors.py", line 30, in wrapper
10:25:38 web    |     response = wrapped(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
10:25:38 web    |     result = view(context, request)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 123, in _class_requestonly_view
10:25:38 web    |     response = getattr(inst, attr)()
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/views/api_auth.py", line 177, in post
10:25:38 web    |     self.request.url, self.request.method, self.request.POST, self.request.headers)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
10:25:38 web    |     return f(endpoint, uri, *args, **kwargs)
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 118, in create_token_response
10:25:38 web    |     request, self.default_token_type)
10:25:38 web    |   File "/Users/robert/hypothesis/repos/h/h/oauth/jwt_grant.py", line 80, in create_token_response
10:25:38 web    |     return headers, e.json, e.status_code
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 81, in json
10:25:38 web    |     return json.dumps(dict(self.twotuples))
10:25:38 web    |   File "/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 69, in twotuples
10:25:38 web    |     if self.uri:
10:25:38 web    | AttributeError: 'InvalidJWTGrantTokenClaimError' object has no attribute 'uri'
```

</details>

### Notes

It looks like the `InvalidJWTGrantTokenClaimError` constructor fails to call the base class `__init__`, which would explain the missing `self.uri` field.

**Comment by rjferrier** [comment]
FYI - I get a different output
```09:46:49 web    | 2018-04-09 09:46:49,886 [1290] [pyramid_debugtoolbar:ERROR] Uncaught AttributeError at http://localhost:5000/api/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2YzI5ZGVkZS0zOTlkLTExZTgtOTM1Mi1iNzEwNWJjNzU1YWUiLCJuYmYiOjE1MjMyNjM2MDksImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC8iLCJleHAiOjE1MjMyNjQyMDksInN1YiI6ImFjY3Q6dV9OQ080Y2F3Vkc3QGxvY2FsaG9zdCJ9.0Kmfam5mpxkZawjkUPhhyI5_0G3hmUl1h16H_5Coh-Q
09:46:49 web    | traceback url: http://localhost:5000/_debug_toolbar/313430313831373634303531303234/exception
09:46:49 web    | Traceback (most recent call last):
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 248, in toolbar_tween
09:46:49 web    |     response = _handler(request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
09:46:49 web    |     result = handler(request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 51, in excview_tween
09:46:49 web    |     request_iface=request_iface.combined
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
09:46:49 web    |     response = view_callable(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 182, in __call__
09:46:49 web    |     return view(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
09:46:49 web    |     return view(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
09:46:49 web    |     return view(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 330, in _authdebug_view
09:46:49 web    |     return view(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
09:46:49 web    |     result = view(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
09:46:49 web    |     response = view(request)
09:46:49 web    |   File "/home/richard/hypothesis/h/h/views/api_exceptions.py", line 48, in json_error
09:46:49 web    |     handle_exception(request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
09:46:49 web    |     response = handler(request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
09:46:49 web    |     reraise(*exc_info)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
09:46:49 web    |     response = handler(request)
09:46:49 web    |   File "/home/richard/hypothesis/h/h/tweens.py", line 20, in conditional_http_tween
09:46:49 web    |     response = handler(request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
09:46:49 web    |     view_name
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
09:46:49 web    |     response = view_callable(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 182, in __call__
09:46:49 web    |     return view(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
09:46:49 web    |     return view(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
09:46:49 web    |     return view(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 354, in _authdebug_view
09:46:49 web    |     return view(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/h/util/cors.py", line 30, in wrapper
09:46:49 web    |     response = wrapped(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
09:46:49 web    |     result = view(context, request)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 123, in _class_requestonly_view
09:46:49 web    |     response = getattr(inst, attr)()
09:46:49 web    |   File "/home/richard/hypothesis/h/h/views/api_auth.py", line 177, in post
09:46:49 web    |     self.request.url, self.request.method, self.request.POST, self.request.headers)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
09:46:49 web    |     return f(endpoint, uri, *args, **kwargs)
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 118, in create_token_response
09:46:49 web    |     request, self.default_token_type)
09:46:49 web    |   File "/home/richard/hypothesis/h/h/oauth/jwt_grant.py", line 80, in create_token_response
09:46:49 web    |     return headers, e.json, e.status_code
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 81, in json
09:46:49 web    |     return json.dumps(dict(self.twotuples))
09:46:49 web    |   File "/home/richard/hypothesis/h/.venv/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 69, in twotuples
09:46:49 web    |     if self.uri:
09:46:49 web    | AttributeError: 'InvalidJWTGrantTokenClaimError' object has no attribute 'uri'```
