### ISSUE TITLE
TypeError: object of type 'type' has no len()

### ISSUE THREAD

**Issue by fishfree** [hypothesis/h#5340]
When I set the admin role to the first registered uer:
`~/h/bin$ ./hypothesis --dev user admin firstuser`
It shows error as below:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/wzzhang/h/h/__main__.py", line 7, in <module>
    main()
  File "h/cli/__init__.py", line 73, in main
    cli.add_command(resolver.resolve(cmd))
  File "/usr/local/lib/python2.7/dist-packages/pyramid/path.py", line 300, in resolve
    return self._resolve(dotted, package)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/path.py", line 327, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/path.py", line 382, in _zope_dottedname_style
    __import__(used)
  File "h/cli/commands/authclient.py", line 5, in <module>
    from h import models
  File "h/models/__init__.py", line 25, in <module>
    from h.models.auth_client import AuthClient
  File "h/models/auth_client.py", line 64, in <module>
    class AuthClient(Base, Timestamps):
  File "h/models/auth_client.py", line 96, in AuthClient
    grant_type = sa.Column(sa.Enum(GrantType, name='authclient_grant_type'), nullable=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/sqltypes.py", line 1296, in __init__
    self._enum_init(enums, kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/sqltypes.py", line 1332, in _enum_init
    length = max(len(x) for x in self.enums)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/sqltypes.py", line 1332, in <genexpr>
    length = max(len(x) for x in self.enums)
TypeError: object of type 'type' has no len()
```

**Comment by robertknight** [comment]
This sounds like this problem: https://bitbucket.org/zzzeek/sqlalchemy/issues/4261/typeerror-while-using-sqlalchemyenum-with

Can you check if you have the "enum" package installed on your system?

Additionally we have recently, in the last two days, updated the setup instructions for h to better isolate its Python environment from the rest of the system using a tool called tox. Can you please have a look at the revised instructions and let us know if you have problems.

**Comment by fishfree** [comment]
@robertknight Running "sudo pip install enum34" works. Thank you!
