### ISSUE TITLE
Make Dev Failure

### ISSUE THREAD

**Issue by ghurson** [hypothesis/h#5346]
### Steps to reproduce
1.  https://github.com/hypothesis/h/blob/master/docs/developing/install.rst
2. The step "Running h"/make dev failed

### Expected behaviour
It should start the server on port 5000

### Actual behaviour
`tox -e py27-dev
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/usr/local/lib/python2.7/site-packages/tox/session.py", line 41, in cmdline
    main(args)
  File "/usr/local/lib/python2.7/site-packages/tox/session.py", line 46, in main
    config = prepare(args)
  File "/usr/local/lib/python2.7/site-packages/tox/session.py", line 28, in prepare
    config = parseconfig(args)
  File "/usr/local/lib/python2.7/site-packages/tox/config.py", line 233, in parseconfig
    pm.hook.tox_configure(config=config)  # post process config object
  File "/usr/local/lib/python2.7/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/site-packages/tox_pip_extensions.py", line 48, in tox_configure
    cfg.read(config.option.configfile)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 300, in read
    for filename in filenames:
TypeError: 'NoneType' object is not iterable
make: *** [dev] Error 1`

### Additional details
macOSX 10.12.6
Python 2.7.15

### Another Thing

In issue 5187, there was a potential fix for a make dev fail issue involving this code:

`./bin/hypothesis --dev migrate upgrade head`

I ran this code in my h directory to see if that could help, got an error that a library was missing, I installed it with pip, than a second one, the third one is sqlalchemy. I ran pip install sqlalchemy and it installs successfully, but then when I run the above command, I get the same missing sqlalchemy module again.

I see that the error message in ticket 5187 is also from sqlalchemy, so I'm wondering if there's a library I'm missing. Is there any other information I can provide to help?

I also tried this on two digital ocean droplets to make sure that I didn't have multiple versions of python running (Ubuntu 18.04 and a premade Docker Container droplet) - exact same errors.

Any thoughts on where I'm going wrong? I'm new to the python world, so I might be missing something pretty simple.

Thanks!

**Comment by fishfree** [comment]
sudo pip uninstall tox
sudo pip install tox=3.3.0
Maybe works.

**Comment by ghurson** [comment]
Aha! A million thank yous!! That did the trick.

There is a user in the slack channel who had the exact same issue, I passed this fix on to them, but this might be a wider spread issue.

Thanks again!!
