### ISSUE TITLE
hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect         sock.connect(self.unix_socket)     PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by raphael10-collab** [hypothesis/h#7596]
raphy@pc:~/hypothesis$ git clone https://github.com/hypothesis/h.git
    Cloning into 'h'...
    remote: Enumerating objects: 114998, done.
    remote: Counting objects: 100% (258/258), done.
    remote: Compressing objects: 100% (140/140), done.
    remote: Total 114998 (delta 182), reused 156 (delta 112), pack-reused 114740
    Receiving objects: 100% (114998/114998), 36.19 MiB | 20.18 MiB/s, done.
    Resolving deltas: 100% (84828/84828), done.
    raphy@pc:~/hypothesis$ cd h
    raphy@pc:~/hypothesis/h$ make services
    Everything up-to-date
    Traceback (most recent call last):
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
        httplib_response = self._make_request(
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/home/raphy/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1256, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/home/raphy/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1302, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/home/raphy/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1251, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/home/raphy/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1011, in _send_output
        self.send(msg)
      File "/home/raphy/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 951, in send
        self.connect()
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
        sock.connect(self.unix_socket)
    PermissionError: [Errno 13] Permission denied
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
        resp = conn.urlopen(
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
        retries = retries.increment(
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
        raise value.with_traceback(tb)
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
        httplib_response = self._make_request(
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/home/raphy/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1256, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/home/raphy/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1302, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/home/raphy/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1251, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/home/raphy/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1011, in _send_output
        self.send(msg)
      File "/home/raphy/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 951, in send
        self.connect()
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
        sock.connect(self.unix_socket)
    urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
        return self.version(api_version=False)["ApiVersion"]
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
        return self._result(self._get(url), json=True)
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
        return f(self, *args, **kwargs)
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
        return self.get(url, **self._set_request_timeout(kwargs))
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
        return self.request('GET', url, **kwargs)
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/raphy/hypothesis/h/.tox/dockercompose/bin/docker-compose", line 8, in <module>
        sys.exit(main())
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/compose/cli/main.py", line 81, in main
        command_func()
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/compose/cli/main.py", line 200, in perform_command
        project = project_from_options('.', options)
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/compose/cli/command.py", line 60, in project_from_options
        return get_project(
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/compose/cli/command.py", line 152, in get_project
        client = get_client(
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/compose/cli/docker_client.py", line 41, in get_client
        client = docker_client(
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/compose/cli/docker_client.py", line 170, in docker_client
        client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
        self._version = self._retrieve_server_version()
      File "/home/raphy/hypothesis/h/.tox/dockercompose/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
        raise DockerException(
    docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
    ERROR: InvocationError for command /home/raphy/hypothesis/h/.tox/dockercompose/bin/docker-compose up -d (exited with code 1)
    ___________________________________ summary ____________________________________
    ERROR:   dockercompose: commands failed
    make: *** [Makefile:34: services] Error 1
    raphy@pc:~/hypothesis/h$ 

Other Info:

    O.S.: Ubuntu 20.04 Desktop
    Python version: 
        raphy@pc:~/hypothesis/h$ python -V
        Python 3.8.12

**Comment by robertknight** [comment]
It looks like the Docker daemon is not running on your system. Have you installed and started Docker?

**Comment by raphael10-collab** [comment]
Hi Robert! Thanks for helping
    
    raphy@pc:~/browser-notes/src/hypothesis/h$ docker -v
    Docker version 20.10.17, build 100c701

Currently no images running:
    
    raphy@pc:~/browser-notes/src/hypothesis/h$ sudo docker ps
    CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

Do I have to download a docker image and a docker container? : https://h.readthedocs.io/en/latest/developing/install/
I'm a bit confused ...

**Comment by raphael10-collab** [comment]
I killed all the `postgres` processes : 

    raphy@pc:~/browser-notes/src/hypothesis/h$ sudo ps xa | grep postgres
       1049 ?        Ss     0:00 /usr/lib/postgresql/12/bin/postgres -D /var/lib/postgresql/12/main -c config_file=/etc/postgresql/12/main/postgresql.conf
       1060 ?        Ss     0:00 postgres: 12/main: checkpointer   
       1061 ?        Ss     0:00 postgres: 12/main: background writer   
       1062 ?        Ss     0:00 postgres: 12/main: walwriter   
       1063 ?        Ss     0:00 postgres: 12/main: autovacuum launcher   
       1064 ?        Ss     0:00 postgres: 12/main: stats collector   
       1065 ?        Ss     0:00 postgres: 12/main: logical replication launcher   
       7575 pts/0    S+     0:00 grep --color=auto postgres
    raphy@pc:~/browser-notes/src/hypothesis/h$ sudo kill 1049 1060 1061 1062 1063 1064 1065


    raphy@pc:~/browser-notes/src/hypothesis/h$ sudo docker ps
    CONTAINER ID   IMAGE                             COMMAND                  CREATED             STATUS         PORTS                                                                                            NAMES
    f6298d69a4aa   rabbitmq:3.6-management-alpine    "docker-entrypoint.s…"   About an hour ago   Up 3 minutes   4369/tcp, 5671/tcp, 127.0.0.1:5672->5672/tcp, 15671/tcp, 25672/tcp, 127.0.0.1:15672->15672/tcp   h_rabbit_1
    b0410778f1e8   hypothesis/elasticsearch:latest   "/usr/local/bin/dock…"   About an hour ago   Up 3 minutes   127.0.0.1:9200->9200/tcp, 9300/tcp            

And now the  'docker compose` seems working fine: 
    
    raphy@pc:~/browser-notes/src/hypothesis/h$ sudo docker-compose up -d
    Starting h_postgres_1 ... 
    h_rabbit_1 is up-to-date
    Starting h_postgres_1 ... done
    raphy@pc:~/browser-notes/src/hypothesis/h$ make services
    h_postgres_1 is up-to-date
    h_rabbit_1 is up-to-date
    h_elasticsearch_1 is up-to-date
    _____________________________________________________________________________________ summary ______________________________________________________________________________________
      dockercompose: commands succeeded
      congratulations :)
